# Generated by Django 4.2 on 2023-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Просмотрена'),
        ),
    ]
